### ISSUE TITLE
Error after starting the program

### ISSUE THREAD

**Issue by DevonVille** [raymontag/keepassc#4]
I'm not much of a python user, so I did try my best.
Not sure if I did right:)

I followed these commands when trying to install:
# Installing python3

``` bash
cd /usr/local/lib
sudo wget http://www.python.org/ftp/python/3.2.3/Python-3.2.3.tgz && sudo tar -xvf Python-3.2.3.tgz
cd Python-3.2.3/
./configure
make
sudo make altinstall
```
# Installing dependencies

``` bash
sudo apt-get install xsel
sudo git clone https://github.com/raymontag/kppy /usr/local/lib/kppy
sudo git clone https://github.com/dlitz/pycrypto /usr/local/lib/pycrypto
cd /usr/local/lib/kppy/ && sudo python3.2 setup.py install
cd /usr/local/lib/pycrypto/ && sudo python3.2 setup.py build && sudo python3.2 setup.py install
```
# Installing KeePassC

``` bash
sudo git clone https://github.com/raymontag/keepassc /usr/local/lib/keepassc
cd /usr/local/lib/keepassc/ && sudo python3.2 setup.py install
```

I then got this error when trying to start my program:

``` bash
Traceback (most recent call last):
  File "/usr/local/bin/keepassc", line 34, in <module>
    from kppy import *
  File "/usr/local/lib/python3.2/site-packages/kppy.py", line 23, in <module>
    from Crypto import Random
ImportError: No module named Crypto
```

Any ideas how to fix would be mucho appreciated.

**Comment by sebma** [comment]
Hi, I had the same `/var/empty` missing problem on my Ubuntu

Can you please add the `mkdir(/var/empty)` in the `setup.py` ?

BTW: ssh does work without this directory:

```
$ ssh b206 
xxxxx@b206's password: 
Welcome to Ubuntu X.Y

 * Documentation:  https://help.ubuntu.com/

Last login: Wed Apr 13 19:17:41 2016 from 192.168.1.2
‘/datas/ImagesVersets/bibliorama.fr/1680_desert.jpg’ -> ‘/boot/grub/today.jpg’
‘/boot/grub/today.jpg’ -> ‘/iso/boot/grub/today.jpg’

     "Be of good courage, and he shall strengthen your
      heart, all ye that hope in the LORD."
                             Psalm 31:24 
xxxxx @ xxxxx-B206 : ~ ls -ld /var/empty
ls: cannot access /var/empty: No such file or directory
```
